### ISSUE TITLE
how to run it in ros

### ISSUE THREAD

**Issue by zhang-mu-zhi** [aimagelab/focus-on-impact#1]
I want to run the algorithm in ross but this algorithm is not packaged so I wonder how to proceed

I'm trying to make a package file myself and proceed, but I'm wondering if there's a better way.

**Comment by Bigazzon** [comment]
Hello,
we did not try to run it with ROS as it was out of the scope of our project, I can only suggest you try [ROS-X-Habitat](https://github.com/ericchen321/ros_x_habitat) bridge.
